spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/minet;
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  header: Authorization
  secret: bGF0ZW5pZ2h0aXNmdWNrZWR1cGJ1dGxhdGVuaWdodGNvZGluZ2lzIE5PVyBSSVNJTkcgaGFoYWhhaGEharegWGRsgsrgsrgsSsgq
  token-validity-in-seconds: 86400